# MySQL Backup com Rclone - Exemplo Docker Compose
# Copie este arquivo para docker-compose.yml e personalize para suas necessidades

version: '3.8'

services:
  mysql-backup:
    image: yourusername/mysql-backup-rclone:latest
    container_name: mysql-backup-rclone
    restart: unless-stopped
    
    environment:
      # Configuração MySQL - OBRIGATÓRIO
      MYSQL_HOST: "seu-host-mysql"
      MYSQL_PORT: 3306
      MYSQL_USER: "seu-usuario-mysql"
      MYSQL_PASSWORD: "sua-senha-mysql"
      MYSQL_DATABASES: "banco1,banco2,banco3"
      
      # Configuração Rclone - OBRIGATÓRIO
      RCLONE_REMOTE: "gdrive:backups/mysql"
      
      # Configuração de Backup - OPCIONAL
      CRON_SCHEDULE: "0 2 * * *"  # Diariamente às 2h da manhã
      BACKUP_RETENTION: 7          # Manter 7 backups locais
      TZ: "America/Sao_Paulo"      # Fuso horário
      LOG_LEVEL: "INFO"            # Nível de log: DEBUG, INFO, WARN, ERROR
      
      # Notificações Webhook - OPCIONAL
      # WEBHOOK_URL: "https://hooks.slack.com/services/YOUR/WEBHOOK/URL"
    
    volumes:
      # Configuração rclone - OBRIGATÓRIO
      - rclone_config:/root/.config/rclone
      
      # Armazenamento de backup - OPCIONAL (para persistência)
      - backup_data:/backup
      
      # Logs - OPCIONAL (para persistência)
      - ./logs:/var/log
    
    networks:
      - mysql-network
    
    healthcheck:
      test: ["CMD-SHELL", "test -f /var/log/cron.log && pgrep cron > /dev/null"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  rclone_config:
    driver: local
  backup_data:
    driver: local

networks:
  mysql-network:
    driver: bridge
